In [3]:
import numpy
from torchvision.datasets import ImageFolder
import re
from PIL import Image
import pandas as pd

First we need to preprocess our data. Images are saved using RGB. We need to convert entire color space into n classes. We will use K-Means clustering algorithm for that.

In [5]:
data = ImageFolder("data/train")
print((data[0][0]))

<PIL.Image.Image image mode=RGB size=320x213 at 0x1173CCD70>


In [6]:
print(data.imgs[0])
print(((data.imgs[0][0]).split("/")[-1]).split(".")[0])

('data/train/all/10043234166_e6dd915111_n.jpg', 0)
10043234166_e6dd915111_n


In [7]:
def img_resize_and_save(image,dir_path,filename):
    resized_img = image.resize((300,200))
    resized_img.save(dir_path + filename+".jpg")

In [8]:
img_resize_and_save(data[0][0],'',((data.imgs[0][0]).split("/")[-1]).split(".")[0])

In [10]:
i = 0
while i < len(data):
    img_resize_and_save(data[i][0],'dataset/resized_color/',((data.imgs[i][0]).split("/")[-1]).split(".")[0])
    i+=1


Now we have a dataset of 300x200 pixels. The next step is to transform them to X -> Y.
For this purpose we will transform those images to grayscale (X) and matrixes of color cluster indexes (Y). In order to achieve that we have to run KMeans algorithm on CIE LAB version of those images (only a and b)

In [5]:
import os
from os import listdir
from PIL import Image, ImageOps

# get the path/directory
folder_dir = "dataset/resized_color"
imagesTable = []
for images in os.listdir(folder_dir):
    # check if the image ends with png
    if (images.endswith(".jpg")):
        with Image.open("dataset/resized_color/" + images) as im:
            im1 = ImageOps.grayscale(im)
            im1.save("dataset/grayscale/" + images)




In [11]:
import numpy as np
from skimage import io, color

rgb_img = io.imread("test.jpg")
print(type(rgb_img))
print(rgb_img[0][0])

rgb_norm = rgb_img / 255.0

print(rgb_norm[0][0])

cie_lab_img = color.rgb2lab(rgb_norm)
print(type(cie_lab_img))


<class 'numpy.ndarray'>
[6 7 2]
[0.02352941 0.02745098 0.00784314]
<class 'numpy.ndarray'>


In [27]:
# test działania konwersji z rgb do cie lab i na odwrót

from skimage import img_as_ubyte
goback = color.lab2rgb(cie_lab_img)
print(goback[0][0])
goback = img_as_ubyte(goback)
print(goback[0][0])
print(io.imsave("t.jpg",goback))

[0.02352941 0.02745098 0.00784314]
[6 7 2]
None
